# List of source files in compilation order (based on makefile dependencies)
sources = [
  'GlobalData.f90',
  'ParticleTrackingOptions.f90',
  'UtilMisc.f90',
  'Coordinate.f90',
  'utl7.f',
  'compilerversion.fpp',
  'BudgetListItem.f90',
  'TrackCellOptions.f90',
  'ModpathUnstructuredBasicData.f90',
  'GridLocation.f90',
  'openspec.f90',
  'HeadRecordHeader.f90',
  'GeoReference.f90',
  'Particle.f90',
  'BudgetRecordHeader.f90',
  'GridLocationList.f90',
  'ParticleLocation.f90',
  'ParticleGroup.f90',
  'utl8.f90',
  'BudgetReader.f90',
  'ModpathSubCellData.f90',
  'HeadReader.f90',
  'TrackSubCellResult.f90',
  'ParticleCoordinate.f90',
  'ParticleLocationPtr.f90',
  'ParticleLocationList.f90',
  'TimeDiscretizationData.f90',
  'ModflowGrid.f90',
  'ParticleCoordinateList.f90',
  'TrackSubCell.f90',
  'ModflowRectangularGrid.f90',
  'RectangularGridDisuMfusg.f90',
  'ParticlePath.f90',
  'StartingLocationReader.f90',
  'ModpathSimulationData.f90',
  'RectangularGridDisuMf6.f90',
  'ModpathBasicData.f90',
  'RectangularGridDisvMf6.f90',
  'ModpathCellData.f90',
  'RectangularGridDisMf6.f90',
  'RectangularGridDis.f90',
  'TrackPathResult.f90',
  'TrackCellResult.f90',
  'TrackCell.f90',
  'ParticleTrackingEngine.f90',
  'ModpathCellDataContainer.f90',
  'ParticleManager.f90',
  'MPath7.f90',
]

exe = executable(
                 'mp7',
                 sources,
                 link_language : 'fortran',
                 install: true
                )
